#TUGAS 2 - Credit Approval Classification with Artificial Neural Networks
MK Pengantar Kecerdasan Tiruan

Nasywa Befiputri - 2203015044

#Import seluruh library yang di butuhkan

In [2]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

#import data frame

In [3]:
client_df = pd.read_csv('https://drive.google.com/uc?id=1_FXPTX8ap2LfgKKVF2zjShieopWDqHwL')
client_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

#pilih fitur dan target

In [4]:
x = client_df.iloc[:, 3:-1].values
y = client_df.iloc[:, -1].values

#ubah atribut gender untuk menjadi nomerik
Male : 1
Female : 0

In [5]:
le = LabelEncoder()

x[:, 2] = le.fit_transform(x[:, 2])

print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#ubah  atribut Geography menjadi 3 kolom dan terletak di kolom 0 hingga 2

Frace = (1,0,0)
Germany = (0,1,0)
Spain = (0,0,1)

In [6]:

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print (x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#split dataset jadi training dan testing

In [7]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

#Scaling atribut menggunakan Standard Scaler. Setelah itu tampilkan data setelah dilakukan scaling

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [ ]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# Proses Training dan Evaluasi menggunakan perhitungan accuracy.

In [ ]:
for nh in range (2,11):
  ann = MLPClassifier(hidden_layer_sizes=(nh,),max_iter=10000, random_state=1)
  ann.fit(x_train, y_train)
  acc = 100*ann.score(x_test,y_test)
  print('Neuron in hidden layer: %g, accuracy %.2f %%'  %(nh,acc))

Neuron in hidden layer: 2, accuracy 83.75 %
Neuron in hidden layer: 3, accuracy 85.15 %
Neuron in hidden layer: 4, accuracy 84.20 %
Neuron in hidden layer: 5, accuracy 86.35 %
Neuron in hidden layer: 6, accuracy 86.15 %
Neuron in hidden layer: 7, accuracy 86.20 %
Neuron in hidden layer: 8, accuracy 85.70 %
Neuron in hidden layer: 9, accuracy 86.25 %
Neuron in hidden layer: 10, accuracy 86.15 %


# Gunakan model ANN dengan jumlah neuron dalam hidden layer berjumlah 3 dikarenakan memiliki akurasi yang terbaik untuk menentukan apakah nasabah di tolak atau diterima

##Anomali



###cek train shape untuk memastikan jumlah input input

In [ ]:
print(x_train.shape)

(8000, 12)


In [ ]:
c= np.array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]])

c[:, 2] = le.transform(c[:, 2])
c = ct.transform(c)
c = sc.transform(c)
pred = ann.predict(c)

if (pred == 0):
    print('tolak')
else:
  print('terima')



tolak


ada ke anehan di output, di modul harusnya 'ditolak', dan kalo kita pertahatihan features itu ad 12, sedangkan ke tidak sesuai dengan data yang tersedia 10, kita cek lagi

##Improve, untuk memaksimalkan akurasi presiksi

In [ ]:
c= np.array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]])
if c.shape[1] == x_train.shape[1]:
    c[:, 2] = le.transform(c[:, 2])
    c = ct.transform
    c = sc.transform(c)
    pred = ann.predict(c)

    if (pred == 0):
        print('tolak')
    else:
      print('terima')
else:
  if (c.shape[1] == 0):
    print("Ditolak, tidak ada data terinput")
  elif (c.shape[1] < x_train.shape[1]):
    print("Ditolak karena data belum lengkap")
  elif (c.shape[1] > x_train.shape[1]):
    print("Ditolak karena data terlalu banyak")
  else:
    print("Ditolak karena data invalid")

Ditolak karena data belum lengkap
